import { ModeToggle } from "@/components/mode-toggle";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manrope.variable} antialiased`}>
        <Providers>
          <header className="hidden md:flex justify-end p-2 top-0 w-full">
            <ModeToggle />
          </header>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
